## News Headline EDA

In [17]:
import sys
import os

sys.path.insert(0, os.path.abspath('C:/Users/dagic/OneDrive/Documents/KAIM/Week_1/news-sentiment-analysis'))

print('Path set. Python will now look in:', os.path.abspath('C:/Users/dagic/OneDrive/Documents/KAIM/Week_1/news-sentiment-analysis'))

Path set. Python will now look in: C:\Users\dagic\OneDrive\Documents\KAIM\Week_1\news-sentiment-analysis

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
from src.data_loader import load_data
from src.data_cleaner import count_null_values, drop_null_values, save_cleaned_data

In [8]:
load_data?

Signature: load_data(file_path)
Docstring:
load data from a csv file,

change 'Date' column to 'date' if it exists,

convert it to datetime format,

set it as index, and sort the data by date
File:      c:\users\dagic\onedrive\documents\kaim\week_1\news-sentiment-analysis\src\data_loader.py
Type:      function

In [9]:
data_name = 'raw_analyst_ratings'
folder_name = 'news_data'
df = load_data(f'../data/raw/{folder_name}/{data_name}.csv')

Shape of data: (1407328, 5)

In [10]:
df.head()

,Unnamed: 0,headline,url,publisher,stock
date,,,,,
2011-04-27 21:01:48-04:00,357064,"ETFs To Watch April 28, 2011 (DGP, IEO, PRN, IDX)",https://www.benzinga.com/etfs/bond-etfs/11/04/...,ETF Professor,DGP
2011-04-28 13:49:29-04:00,437774,A New Regional Emerging Markets ETF,https://www.benzinga.com/etfs/emerging-market-...,Sam Subramanian,ESR
2011-04-28 15:00:36-04:00,350150,Dejour Extends Credit Facility to October 31st...,https://www.benzinga.com/news/11/04/1041764/de...,Theo Kratz,DEJ
2011-04-29 13:47:06-04:00,49280,"ETF Showdown: Crouching Tigers, Hidden ETFs",https://www.benzinga.com/etfs/emerging-market-...,ETF Professor,AIA
2011-04-29 16:11:05-04:00,539428,The GDL Fund to Redeem Its Outstanding 8.50% S...,https://www.benzinga.com/news/11/04/1045464/th...,Benzinga Staff,GDL

## 1. Data Cleaning

In [19]:
df = count_null_values(df, data_name)

Null values in raw_analyst_ratings:
Unnamed: 0    0
headline      0
url           0
publisher     0
stock         0
dtype: int64

In [27]:
df = drop_null_values(df, data_name)
df = save_cleaned_data(df, data_name)
df.head()

Shape of data after dropping null values for raw_analyst_ratings: (1407328, 5)
Shape of cleaned raw_analyst_ratings: (1407328, 5)
First 5 rows of cleaned raw_analyst_ratings:
                           Unnamed: 0  \
date
2011-04-27 21:01:48-04:00      357064
2011-04-28 13:49:29-04:00      437774
2011-04-28 15:00:36-04:00      350150
2011-04-29 13:47:06-04:00       49280
2011-04-29 16:11:05-04:00      539428

                                                                    headline  \
date
2011-04-27 21:01:48-04:00  ETFs To Watch April 28, 2011 (DGP, IEO, PRN, IDX)
2011-04-28 13:49:29-04:00                A New Regional Emerging Markets ETF
2011-04-28 15:00:36-04:00  Dejour Extends Credit Facility to October 31st...
2011-04-29 13:47:06-04:00        ETF Showdown: Crouching Tigers, Hidden ETFs
2011-04-29 16:11:05-04:00  The GDL Fund to Redeem Its Outstanding 8.50% S...

                                                                         url  \
date
2011-04-27 21:01:48-04:00  https://www.benzinga.com/etfs/bond-etfs/11/04/...
2011-04-28 13:49:29-04:00  https://www.benzinga.com/etfs/emerging-market-...
2011-04-28 15:00:36-04:00  https://www.benzinga.com/news/11/04/1041764/de...
2011-04-29 13:47:06-04:00  https://www.benzinga.com/etfs/emerging-market-...
2011-04-29 16:11:05-04:00  https://www.benzinga.com/news/11/04/1045464/th...

                                 publisher stock
date
2011-04-27 21:01:48-04:00    ETF Professor   DGP
2011-04-28 13:49:29-04:00  Sam Subramanian   ESR
2011-04-28 15:00:36-04:00       Theo Kratz   DEJ
2011-04-29 13:47:06-04:00    ETF Professor   AIA
2011-04-29 16:11:05-04:00   Benzinga Staff   GDL

,Unnamed: 0,headline,url,publisher,stock
date,,,,,
2011-04-27 21:01:48-04:00,357064,"ETFs To Watch April 28, 2011 (DGP, IEO, PRN, IDX)",https://www.benzinga.com/etfs/bond-etfs/11/04/...,ETF Professor,DGP
2011-04-28 13:49:29-04:00,437774,A New Regional Emerging Markets ETF,https://www.benzinga.com/etfs/emerging-market-...,Sam Subramanian,ESR
2011-04-28 15:00:36-04:00,350150,Dejour Extends Credit Facility to October 31st...,https://www.benzinga.com/news/11/04/1041764/de...,Theo Kratz,DEJ
2011-04-29 13:47:06-04:00,49280,"ETF Showdown: Crouching Tigers, Hidden ETFs",https://www.benzinga.com/etfs/emerging-market-...,ETF Professor,AIA
2011-04-29 16:11:05-04:00,539428,The GDL Fund to Redeem Its Outstanding 8.50% S...,https://www.benzinga.com/news/11/04/1045464/th...,Benzinga Staff,GDL

In [29]:
df = pd.read_csv('../data/processed/cleaned_raw_analyst_ratings.csv')
df.head()

C:\Users\dagic\AppData\Local\Temp\ipykernel_4452\868548531.py:1: DtypeWarning: Columns (0: date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/processed/cleaned_raw_analyst_ratings.csv')

,date,Unnamed: 0,headline,url,publisher,stock
0,2011-04-27 21:01:48-04:00,357064,"ETFs To Watch April 28, 2011 (DGP, IEO, PRN, IDX)",https://www.benzinga.com/etfs/bond-etfs/11/04/...,ETF Professor,DGP
1,2011-04-28 13:49:29-04:00,437774,A New Regional Emerging Markets ETF,https://www.benzinga.com/etfs/emerging-market-...,Sam Subramanian,ESR
2,2011-04-28 15:00:36-04:00,350150,Dejour Extends Credit Facility to October 31st...,https://www.benzinga.com/news/11/04/1041764/de...,Theo Kratz,DEJ
3,2011-04-29 13:47:06-04:00,49280,"ETF Showdown: Crouching Tigers, Hidden ETFs",https://www.benzinga.com/etfs/emerging-market-...,ETF Professor,AIA
4,2011-04-29 16:11:05-04:00,539428,The GDL Fund to Redeem Its Outstanding 8.50% S...,https://www.benzinga.com/news/11/04/1045464/th...,Benzinga Staff,GDL

## 2. Data Exploration

In [30]:
print("Data shape:", df.shape)
print("\nColumn names and types:")
print(df.dtypes)
print("\nFirst few rows:")
print(df.head(10))
print("\nData info:")
print(df.info())

Data shape: (1407328, 6)

Column names and types:
date            str
Unnamed: 0    int64
headline        str
url             str
publisher       str
stock           str
dtype: object

First few rows:
                        date  Unnamed: 0  \
0  2011-04-27 21:01:48-04:00      357064
1  2011-04-28 13:49:29-04:00      437774
2  2011-04-28 15:00:36-04:00      350150
3  2011-04-29 13:47:06-04:00       49280
4  2011-04-29 16:11:05-04:00      539428
5  2011-04-30 16:52:35-04:00     1041943
6  2011-05-01 18:18:28-04:00      341543
7  2011-05-02 02:17:31-04:00      341542
8  2011-05-02 03:24:46-04:00     1358811
9  2011-05-02 03:24:46-04:00       46024

                                            headline  \
0  ETFs To Watch April 28, 2011 (DGP, IEO, PRN, IDX)
1                A New Regional Emerging Markets ETF
2  Dejour Extends Credit Facility to October 31st...
3        ETF Showdown: Crouching Tigers, Hidden ETFs
4  The GDL Fund to Redeem Its Outstanding 8.50% S...
5  Benzinga's Top ETF Gainers, April 29th (PTM, B...
6    ETFs To Watch May 2, 2011 (EUO, EWT, CRUD, TAN)
7           Play bin Laden's Capture With These ETFs
8              ETF Securities Reportedly Mulling IPO
9              ETF Securities Reportedly Mulling IPO

                                                 url        publisher stock
0  https://www.benzinga.com/etfs/bond-etfs/11/04/...    ETF Professor   DGP
1  https://www.benzinga.com/etfs/emerging-market-...  Sam Subramanian   ESR
2  https://www.benzinga.com/news/11/04/1041764/de...       Theo Kratz   DEJ
3  https://www.benzinga.com/etfs/emerging-market-...    ETF Professor   AIA
4  https://www.benzinga.com/news/11/04/1045464/th...   Benzinga Staff   GDL
5  https://www.benzinga.com/etfs/commodity-etfs/1...      Craig Jones   PTM
6  https://www.benzinga.com/etfs/bond-etfs/11/05/...    ETF Professor   DBP
7  https://www.benzinga.com/etfs/commodity-etfs/1...    ETF Professor   DBP
8  https://www.benzinga.com/etfs/commodity-etfs/1...    ETF Professor  WITE
9  https://www.benzinga.com/etfs/commodity-etfs/1...    ETF Professor  AGOL

Data info:
<class 'pandas.DataFrame'>
RangeIndex: 1407328 entries, 0 to 1407327
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   date        55987 non-null    str
 1   Unnamed: 0  1407328 non-null  int64
 2   headline    1407328 non-null  str
 3   url         1407328 non-null  str
 4   publisher   1407328 non-null  str
 5   stock       1407328 non-null  str
dtypes: int64(1), str(5)
memory usage: 334.0 MB
None

## 2. Descriptive Statistics

In [32]:
import numpy as np

# Identify text columns (headlines, titles, content)
text_columns = df.select_dtypes(include=['str']).columns.tolist()
print("Text columns found:", text_columns)

# For each text column, calculate character count statistics
for col in text_columns:
    if col in df.columns and df[col].dtype == 'str':
        char_counts = df[col].astype(str).str.len()
        word_counts = df[col].astype(str).str.split().str.len()
        
        print(f"\n--- {col} Statistics ---")
        print(f"Character Count - Mean: {char_counts.mean():.2f}, Median: {char_counts.median():.2f}, Std: {char_counts.std():.2f}")
        print(f"Character Count - Min: {char_counts.min()}, Max: {char_counts.max()}")
        print(f"Word Count - Mean: {word_counts.mean():.2f}, Median: {word_counts.median():.2f}, Std: {word_counts.std():.2f}")
        print(f"Word Count - Min: {word_counts.min()}, Max: {word_counts.max()}")

Text columns found: ['date', 'headline', 'url', 'publisher', 'stock']

--- date Statistics ---
Character Count - Mean: 25.00, Median: 25.00, Std: 0.00
Character Count - Min: 25.0, Max: 25.0
Word Count - Mean: 2.00, Median: 2.00, Std: 0.00
Word Count - Min: 2.0, Max: 2.0

--- headline Statistics ---
Character Count - Mean: 73.12, Median: 64.00, Std: 40.74
Character Count - Min: 3, Max: 512
Word Count - Mean: 11.42, Median: 10.00, Std: 6.35
Word Count - Min: 1, Max: 77

--- url Statistics ---
Character Count - Mean: 110.50, Median: 115.00, Std: 19.17
Character Count - Min: 33, Max: 162
Word Count - Mean: 1.00, Median: 1.00, Std: 0.00
Word Count - Min: 1, Max: 1

--- publisher Statistics ---
Character Count - Mean: 12.77, Median: 13.00, Std: 2.70
Character Count - Min: 3, Max: 46
Word Count - Mean: 1.95, Median: 2.00, Std: 0.30
Word Count - Min: 1, Max: 9

--- stock Statistics ---
Character Count - Mean: 3.34, Median: 3.00, Std: 0.67
Character Count - Min: 1, Max: 5
Word Count - Mean: 1.00, Median: 1.00, Std: 0.00
Word Count - Min: 1, Max: 1

In [ ]:
# Visualize text length distributions
import seaborn as sns

fig, axes = plt.subplots(len(text_columns), 2, figsize=(14, 4*len(text_columns)))
if len(text_columns) == 1:
    axes = [axes]

for idx, col in enumerate(text_columns):
    char_counts = df[col].astype(str).str.len()
    word_counts = df[col].astype(str).str.split().str.len()
    
    sns.histplot(char_counts, kde=True, ax=axes[idx][0])
    axes[idx][0].set_title(f'{col} - Character Count Distribution')
    axes[idx][0].set_xlabel('Character Count')
    
    sns.histplot(word_counts, kde=True, ax=axes[idx][1], color='orange')
    axes[idx][1].set_title(f'{col} - Word Count Distribution')
    axes[idx][1].set_xlabel('Word Count')

plt.tight_layout()
plt.show()

## 3. Publisher Analysis

In [ ]:
# Identify publisher columns (source, publisher, author, etc.)
publisher_columns = [col for col in df.columns if any(term in col.lower() for term in ['source', 'publisher', 'author', 'email', 'origin'])]
print("Potential publisher columns:", publisher_columns)

# If publisher columns exist, analyze them
if publisher_columns:
    for pub_col in publisher_columns:
        print(f"\n--- {pub_col} Analysis ---")
        pub_counts = df[pub_col].value_counts()
        print(f"Total unique values: {df[pub_col].nunique()}")
        print(f"\nTop 20 {pub_col}:")
        print(pub_counts.head(20))
        
        # Extract domains if email-like values exist
        email_like = df[pub_col].astype(str).str.contains('@', na=False).any()
        if email_like:
            print(f"\nEmail-like values detected in {pub_col}")
            domains = df[pub_col].astype(str).str.extract(r'@(.+)')[0].dropna().value_counts()
            print(f"Top domains:")
            print(domains.head(10))
else:
    print("No explicit publisher columns found. Checking all columns for publisher info...")

In [ ]:
# Visualize publisher distribution
if publisher_columns:
    for pub_col in publisher_columns:
        top_n = min(15, df[pub_col].nunique())
        pub_counts = df[pub_col].value_counts().head(top_n)
        
        plt.figure(figsize=(12, 6))
        pub_counts.plot(kind='barh')
        plt.title(f'Top {top_n} {pub_col}')
        plt.xlabel('Article Count')
        plt.ylabel(pub_col)
        plt.tight_layout()
        plt.show()

## 4. Publication Date Analysis

In [ ]:
# Identify date columns
date_columns = [col for col in df.columns if any(term in col.lower() for term in ['date', 'time', 'published', 'created'])]
print("Potential date columns:", date_columns)

# Parse and analyze date columns
date_col = None
for col in date_columns:
    try:
        df[f'{col}_parsed'] = pd.to_datetime(df[col])
        date_col = f'{col}_parsed'
        print(f"\nSuccessfully parsed {col}")
        print(f"Date range: {df[date_col].min()} to {df[date_col].max()}")
        print(f"Total days span: {(df[date_col].max() - df[date_col].min()).days}")
        break
    except:
        continue

if date_col:
    # Extract date/time features
    df['date_only'] = df[date_col].dt.date
    df['hour'] = df[date_col].dt.hour
    df['day_of_week'] = df[date_col].dt.day_name()
    df['month'] = df[date_col].dt.month
    df['year'] = df[date_col].dt.year
    
    print("\n--- Article Distribution by Time ---")
    print(f"Articles per day: {df.groupby('date_only').size().describe()}")
    print(f"\nArticles per hour (24h):\n{df['hour'].value_counts().sort_index()}")
    print(f"\nArticles per day of week:\n{df['day_of_week'].value_counts()}")
else:
    print("No valid date columns found")

In [ ]:
# Time series visualizations
if date_col:
    fig, axes = plt.subplots(2, 2, figsize=(16, 10))
    
    # Articles over time
    daily_counts = df.groupby('date_only').size()
    axes[0, 0].plot(daily_counts.index, daily_counts.values, linewidth=1)
    axes[0, 0].set_title('Article Volume Over Time')
    axes[0, 0].set_xlabel('Date')
    axes[0, 0].set_ylabel('Number of Articles')
    axes[0, 0].grid(True, alpha=0.3)
    
    # Hour of day distribution
    hourly_counts = df['hour'].value_counts().sort_index()
    axes[0, 1].bar(hourly_counts.index, hourly_counts.values, color='steelblue')
    axes[0, 1].set_title('Articles by Hour of Day')
    axes[0, 1].set_xlabel('Hour (0-23)')
    axes[0, 1].set_ylabel('Count')
    axes[0, 1].grid(True, alpha=0.3, axis='y')
    
    # Day of week distribution
    day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    dow_counts = df['day_of_week'].value_counts().reindex(day_order)
    axes[1, 0].bar(range(len(dow_counts)), dow_counts.values, color='coral')
    axes[1, 0].set_xticks(range(len(dow_counts)))
    axes[1, 0].set_xticklabels([d[:3] for d in dow_counts.index], rotation=0)
    axes[1, 0].set_title('Articles by Day of Week')
    axes[1, 0].set_ylabel('Count')
    axes[1, 0].grid(True, alpha=0.3, axis='y')
    
    # Monthly distribution
    monthly_counts = df['month'].value_counts().sort_index()
    axes[1, 1].bar(monthly_counts.index, monthly_counts.values, color='mediumseagreen')
    axes[1, 1].set_title('Articles by Month')
    axes[1, 1].set_xlabel('Month')
    axes[1, 1].set_ylabel('Count')
    axes[1, 1].grid(True, alpha=0.3, axis='y')
    
    plt.tight_layout()
    plt.show()

## 5. Text Analysis - Keywords & Topics

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download required NLTK data
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

# Prepare text data - combine all text columns
all_text = df[text_columns].fillna('').astype(str).agg(' '.join, axis=1)
print(f"Total text samples: {len(all_text)}")
print(f"\nFirst sample:\n{all_text.iloc[0][:200]}...")

In [ ]:
# TF-IDF Analysis to find important keywords
stop_words = set(stopwords.words('english'))

tfidf = TfidfVectorizer(max_features=100, stop_words='english', min_df=2, max_df=0.8)
tfidf_matrix = tfidf.fit_transform(all_text)

# Get top TF-IDF terms
feature_names = tfidf.get_feature_names_out()
tfidf_scores = tfidf_matrix.sum(axis=0).A1
top_indices = np.argsort(tfidf_scores)[-30:][::-1]

print("=== Top 30 Keywords by TF-IDF Score ===")
for idx in top_indices:
    print(f"{feature_names[idx]}: {tfidf_scores[idx]:.4f}")

# Visualize top keywords
fig, ax = plt.subplots(figsize=(12, 8))
top_20 = top_indices[:20]
ax.barh(range(len(top_20)), tfidf_scores[top_20])
ax.set_yticks(range(len(top_20)))
ax.set_yticklabels([feature_names[i] for i in top_20])
ax.set_xlabel('TF-IDF Score')
ax.set_title('Top 20 Keywords (TF-IDF)')
ax.invert_yaxis()
plt.tight_layout()
plt.show()

In [ ]:
# CountVectorizer - Raw term frequencies
count_vec = CountVectorizer(max_features=100, stop_words='english', min_df=2, max_df=0.8)
count_matrix = count_vec.fit_transform(all_text)

# Get most frequent terms
feature_names_cv = count_vec.get_feature_names_out()
count_scores = count_matrix.sum(axis=0).A1
top_indices_cv = np.argsort(count_scores)[-30:][::-1]

print("\n=== Top 30 Most Frequent Terms ===")
for idx in top_indices_cv:
    print(f"{feature_names_cv[idx]}: {int(count_scores[idx])}")

# Visualize term frequencies
fig, ax = plt.subplots(figsize=(12, 8))
top_20_cv = top_indices_cv[:20]
ax.barh(range(len(top_20_cv)), count_scores[top_20_cv], color='steelblue')
ax.set_yticks(range(len(top_20_cv)))
ax.set_yticklabels([feature_names_cv[i] for i in top_20_cv])
ax.set_xlabel('Frequency')
ax.set_title('Top 20 Most Frequent Terms')
ax.invert_yaxis()
plt.tight_layout()
plt.show()

In [ ]:
# Latent Dirichlet Allocation (LDA) for Topic Modeling
n_topics = 5
print(f"\n=== LDA Topic Modeling (n_topics={n_topics}) ===\n")

lda = LatentDirichletAllocation(n_components=n_topics, random_state=42, max_iter=10)
lda.fit(count_matrix)

# Display topics
for topic_idx, topic in enumerate(lda.components_):
    top_features_idx = topic.argsort()[-10:][::-1]
    top_features = [feature_names_cv[i] for i in top_features_idx]
    weights = topic[top_features_idx]
    
    print(f"Topic {topic_idx + 1}:")
    for feature, weight in zip(top_features, weights):
        print(f"  {feature}: {weight:.4f}")
    print()

# Get topic distribution for first 10 documents
doc_topics = lda.transform(count_matrix)
print("=== Document-Topic Distribution (first 5 documents) ===")
print(f"Shape: {doc_topics.shape}")
print(f"\nFirst 5 documents:\n{pd.DataFrame(doc_topics[:5], columns=[f'Topic {i+1}' for i in range(n_topics)]).round(4)}")

In [ ]:
# Visualize topic distribution
dominant_topics = doc_topics.argmax(axis=1)
topic_dist = pd.Series(dominant_topics).value_counts().sort_index()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Topic distribution
axes[0].bar(topic_dist.index + 1, topic_dist.values, color='teal')
axes[0].set_xlabel('Topic')
axes[0].set_ylabel('Number of Documents')
axes[0].set_title('Distribution of Dominant Topics')
axes[0].set_xticks(range(1, n_topics + 1))

# Topic heatmap (average weight per topic across all documents)
avg_topic_dist = doc_topics.mean(axis=0)
axes[1].bar(range(1, n_topics + 1), avg_topic_dist, color='coral')
axes[1].set_xlabel('Topic')
axes[1].set_ylabel('Average Weight')
axes[1].set_title('Average Topic Weights Across All Documents')
axes[1].set_xticks(range(1, n_topics + 1))

plt.tight_layout()
plt.show()

# Add dominant topic to dataframe
df['dominant_topic'] = dominant_topics + 1
print("\n=== Articles per Topic ===")
print(df['dominant_topic'].value_counts().sort_index())

In [ ]:
# Detect recurring themes and specific keywords
recurring_themes = {
    'FDA/Regulatory': [r'\bfda\b', r'\breulatory', r'\bapproval\b', r'\bclinical trial', r'\bfda approval'],
    'Price/Valuation': [r'\bprice target', r'\bstock price', r'\bvaluation', r'\bupgrade', r'\bdowngrade', r'\boverweight', r'\bunderweight'],
    'Earnings': [r'\bearning', r'\beps\b', r'\bevenue\b', r'\bquarterly\b', r'\bq[1-4]\b', r'\beat', r'\bmiss'],
    'Merger/Acquisition': [r'\bmerger\b', r'\bacquisition\b', r'\bacquire', r'\btakeover', r'\bdeal\b'],
    'Technology': [r'\bai\b', r'\bartificial intelligence', r'\bdata', r'\bcloud', r'\bsoftware', r'\bdigital'],
    'Market/Economic': [r'\bmarket\b', r'\beconomy\b', r'\brecession\b', r'\binflation\b', r'\binterest rate'],
}

print("=== Recurring Themes Detection ===\n")
for theme, patterns in recurring_themes.items():
    combined_pattern = '|'.join(f'({p})' for p in patterns)
    matching_articles = all_text.str.lower().str.contains(combined_pattern, regex=True, na=False).sum()
    pct = (matching_articles / len(all_text)) * 100
    print(f"{theme}: {matching_articles} articles ({pct:.2f}%)")

# Count individual significant keywords/phrases
print("\n=== Specific Keywords/Phrases Frequency ===\n")
keywords_to_track = [
    ('FDA Approval', r'\bfda approval'),
    ('Price Target', r'\bprice target'),
    ('Earnings Beat', r'\bearnings? beat'),
    ('Analyst Rating', r'\banalyst|rating'),
    ('AI/Machine Learning', r'\b(?:ai|artificial intelligence|machine learning)\b'),
    ('Cloud Computing', r'\bcloud'),
    ('Cybersecurity', r'\bcybersecurity|security breach'),
]

for keyword, pattern in keywords_to_track:
    count = all_text.str.lower().str.contains(pattern, regex=True, na=False).sum()
    pct = (count / len(all_text)) * 100
    print(f"{keyword}: {count} ({pct:.2f}%)")

## 6. Summary & Key Insights

In [ ]:
print("="*70)
print("HEADLINE EDA - COMPREHENSIVE SUMMARY")
print("="*70)

print(f"\n📊 DATASET OVERVIEW:")
print(f"  • Total articles: {len(df):,}")
print(f"  • Unique publishers: {df[publisher_columns[0]].nunique() if publisher_columns else 'N/A'}")
print(f"  • Date range: {df[date_col].min() if date_col else 'N/A'} to {df[date_col].max() if date_col else 'N/A'}")

if text_columns:
    print(f"\n📝 TEXT STATISTICS:")
    for col in text_columns:
        char_counts = df[col].astype(str).str.len()
        print(f"  • {col}: avg {char_counts.mean():.0f} chars (range: {char_counts.min()}-{char_counts.max()})")

print(f"\n⏰ PUBLICATION PATTERNS:")
if date_col:
    print(f"  • Peak hour: {df['hour'].value_counts().idxmax()}:00")
    print(f"  • Most active day: {df['day_of_week'].value_counts().index[0]}")
    print(f"  • Avg articles/day: {len(df) / df['date_only'].nunique():.0f}")

print(f"\n🔤 TEXT THEMES:")
print(f"  • Top keyword: {feature_names[top_indices[0]]}")
print(f"  • Total unique terms analyzed: {len(feature_names)}")
print(f"  • Number of topics extracted: {n_topics}")

print(f"\n📌 KEY FINDINGS:")
print(f"  • Text analysis identifies market sentiment drivers")
print(f"  • Publication timing shows clear daily/weekly patterns")
print(f"  • Dominant content themes align with financial markets")
print("\n" + "="*70)